plugins {
    id 'java'
}

group = 'mk.ukim.finki'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // Поддршка за JUnit 5 платформата за тестирање
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}
